### ISSUE TITLE
master branch가 아니더라도 PR 제약을 걸 수 있나요? 

### ISSUE THREAD

**Issue by insurgent92** [KerasKorea/KEKOxTutorial#117]
master branch는 code review 이후에 PR이 가능하잖아요?
혹시 master가 아닌 다른 branch로 그렇게 만들 수 있나요?

**Comment by MijeongJeon** [comment]
그럼요~ 다른 branch에도 제한을 걸 수 있답니다.
이 repo에서는 제가 master에만 걸어두었답니다. 혹시 다른 branch도 제한이 필요하신가요?

**Comment by insurgent92** [comment]
@MijeongJeon 네! Issue 40의 내용이 너무 많아서
intermediate branch에 하나씩 PR하는 방식으로 code review를 받고 
최종적으로 master merge하는게 어떨까 싶었습니다.

**Comment by MijeongJeon** [comment]
@insurgent92 아하! 그렇군요. 좋습니다. 그럼 issue_40에 제한 걸어드리겠습니다!

**Comment by insurgent92** [comment]
@insurgent92 감사합니다!
