### ISSUE TITLE
#89 에 review를 처음 달아봤습니다. 

### ISSUE THREAD

**Issue by insurgent92** [KerasKorea/KEKOxTutorial#122]
RP 열자마자 review를 부탁하는 팝업이 뜨길래 그대로 리뷰를 시작했는데.
이렇게 하는게 맞는지 모르겠습니다 :( 
https://github.com/KerasKorea/KEKOxTutorial/pull/90#pullrequestreview-160758883

review에 대한 review 부탁드립니다.. ㅋㅋ

**Comment by MijeongJeon** [comment]
멋진 리뷰입니다. 올바른 방식으로 리뷰 달아주셨어요! 앞으로도 쭈욱~~ 👍

**Comment by insurgent92** [comment]
@MijeongJeon 감사합니다!
