### ISSUE TITLE
#89 GAN 이해하기에서 discriminator.trainable 설정 관련

### ISSUE THREAD

**Issue by tykimos** [KerasKorea/KEKOxTutorial#139]
왕성한 활동 하신다고 고생많으십니다. 작성하신 GAN 관련 코드에서 봐줬으면 하는 부분이 있습니다. 먼저 아래글 간단하게 읽어주세요~

https://tykimos.github.io/2017/12/12/One_Slide_GAN/

작성 코드에서, 학습 과정에 discriminator.trainable의 플래그를 바꾸는 부분이 나오는데, 이 플래그는 컴파일할 때만 적용되므로 컴파일 이후에는 아무 영향이 없을 듯 합니다. 한 번 확인 부탁드려요~

            # Discriminator를 학습시킵니다.
            discriminator.trainable = True
            discriminator.train_on_batch(X, y_dis)

            # Generator를 학습시킵니다.
            noise = np.random.normal(0, 1, size=[batch_size, random_dim])
            y_gen = np.ones(batch_size)
            discriminator.trainable = False

**Comment by parkjh688** [comment]
아하.. 한 번 읽어보고 다시 확인해보겠습니다~
고맙습니다!

**Comment by tykimos** [comment]
네네 맞습니다. 컴파일 할 때, 옵티마이져한테 넘길 플래그 (trainable)이기에, 컴파일이 이뤄지지 않는다면, 소용이 없습니다~

**Comment by parkjh688** [comment]
꼼꼼한 리뷰 감사합니다!
