### ISSUE TITLE
#40 Keras와 Jupyter Notebook으로 시작하는 딥러닝 PR 및 리뷰 관련 

### ISSUE THREAD

**Issue by insurgent92** [KerasKorea/KEKOxTutorial#173]
#40 은 `FRANÇOIS CHOLLET`의 저서인 `Deep learning with python`의 [실습노트](https://github.com/fchollet/deep-learning-with-python-notebooks)입니다. 
#40 을 저와(@insurgent92) @Domirae @RyanKor 님께서 작업해주셨습니다. 
컨텐츠가 많아서 작업 기간이 상당했는데, 안타깝게도 길벗 출판사에서 
`Deep learning with python`의 번역본인 `케라스 창시자에게 배우는 딥러닝`이 
이라는 번역본이 나오면서, [한글 실습노트](https://github.com/gilbutITbook/006975)가 나왔습니다.

우리가 번역한 내용은 50% 정도 진행되었고 우선은 잠정적으로 일시정지를 한 상태입니다.
우선 50% 작업한 내용을 PR 요청을 하였습니다. 코드리뷰 자체도 비용인지라. 
해당 PR에 대한 코드리뷰를 어떻게 하면 좋을까요?

**Comment by MijeongJeon** [comment]
😢 😭 😞  열심히 작업해주셨는데 출판이라니ㅜ 너무 아쉽네요. 그래도 지금까지 작업했으니 동일한 내용이더라도 간단히 리뷰하고 머지하는게 어떨까요?

**Comment by mike2ox** [comment]
저도 일단 PR은 하고 해당 작업 부분에 대해선 원작자와 `케라스 창시자에게 배우는 딥러닝` 한글 실습 노트 역자께 문의해서 케라스팀에서 오픈 프로젝트 형식으로 독자적으로 번역해도 되는지 문의 드려야할 거같아요. 이게 책이 발간된 시점에서 금전문제가 엮일 수 있다고 봅니다.

**Comment by insurgent92** [comment]
@MijeongJeon @mike2ox 의견 감사합니다!
오늘 내로 머지를 하는 것이 좋을까요? 
오늘 review 하기엔 비용이 부담되기는 하네요 :(
