### ISSUE TITLE
Keras/examples (3): Generative models examples

### ISSUE THREAD

**Issue by MijeongJeon** [KerasKorea/KEKOxTutorial#25]
### Keras/examples (3): Generative models examples
[링크](https://github.com/keras-team/keras/tree/master/examples)

**Comment by mike2ox** [comment]
[deep_dream.py](https://github.com/keras-team/keras/blob/master/examples/deep_dream.py), [neural_style_transfer.py](https://github.com/keras-team/keras/blob/master/examples/neural_style_transfer.py) 진행
