### ISSUE TITLE
Keras를 이용해 seq2seq를 10분안에 알려주기

### ISSUE THREAD

**Issue by MijeongJeon** [KerasKorea/KEKOxTutorial#28]
### A ten-minute introduction to sequence-to-sequence learning in Keras
[링크](https://blog.keras.io/a-ten-minute-introduction-to-sequence-to-sequence-learning-in-keras.html)

**Comment by mike2ox** [comment]
merge가 완료됨.
추가 변동 사항이 있을시 reopen.
