### ISSUE TITLE
튜토리얼과 진짜 데이터의 데이터셋 차이에 대해 도움을 받고싶습니다.

### ISSUE THREAD

**Issue by parkjh688** [KerasKorea/KEKOxTutorial#60]
안녕하세요. 저는 `issue 38  Keras와 텐서플로우를 이용한 손글씨 인식` 을 번역하고 있습니다.
번역은 다 끝나고 코드부분을 보고있는데
튜토리얼에서 데이터셋을 가져오는 부분이 아무리 생각해도 진짜 데이터 셋의 디렉토리 구조와
맞지 않는 것 같습니다.

원작자가 쓴 글의 댓글에 그에대해 질문을 했지만 꽤 오랜 시간이 흘렀는데도
답변이 없습니다. 이런 경우에는 어떻게 해야할까요?

**Comment by mike2ox** [comment]
@parkjh688 
priya-dwivedi 깃헙 이슈에 직접 남기면 어떨까요?
그리고 혹시 데이터셋 내부에 png 파일이 아예 없나요?

**Comment by parkjh688** [comment]
아하 깃헙이슈에 남기는것이 좋은 방법이겠네요. 데이터셋을 다른 곳에서 받아오는데 구조가 달라서 코드를 바로 실행해 볼 수 가 없네요..

**Comment by mike2ox** [comment]
원작자 깃레포에서 주피터 노트북이랑 파이썬 파일 둘을 비교해서 보았는데 거기서도 약간 차이가 있더라구요.
원작자 깃레포에 이슈 남겨서 해결해보죠 ㅎㅎ

**Comment by parkjh688** [comment]
네 이슈 남겨야겠어요. 고맙습니다!
