### ISSUE TITLE
용어 관련 질문입니다. 

### ISSUE THREAD

**Issue by nuxlear** [KerasKorea/KEKOxTutorial#71]
먼저 번역 중에 궁금한 단어가 나왔습니다. 

다른 분들은 epoch과 parameter를 어떻게 번역하시나요?
저는 일단 에폭, 파라미터 라고 그대로 번역했는데, 혹 대체할 만한 다른 단어가 있는지 궁금합니다. 

그리고 #51 에서 전체 모임이나 투표로 용어를 만장일치해서 정하자고 하셨는데, 온라인이라면 슬랙에서 진행하나요?
오프라인 참가는 일정 상 어려워서, 어떻게 진행될 지 궁금합니다 :)

**Comment by mike2ox** [comment]
@nuxlear 
제 의견이라 아직 전원이 동의하진 않았으나, 
슬랙에서 진행하고 있었으니 슬랙을 이용하지 않을까 싶습니다.

**Comment by insurgent92** [comment]
epoch같은 경우 그냥 epoch, 혹은 에폭
parameter는 파라미터, 매개변수, parameter 등으로 쓰시면 될것같습니다.
문맥에서 일관성만 유지시켜주면 되지않을까요?

**Comment by Domirae** [comment]
저는 epoch는 그대로 사용했고 parameter는 매개변수로 번역했습니다!

**Comment by nuxlear** [comment]
아하, 그럼 저도 일단 에폭과 파라미터로 사용하겠습니다 :)
