### ISSUE TITLE
완성된 초안에 대한 리뷰시스템은 어떻게 진행하나요?

### ISSUE THREAD

**Issue by insurgent92** [KerasKorea/KEKOxTutorial#77]
제가 만든 초안에 대한 피드백을 받고싶은데
어떤 채널로 하는게 좋을까요?

**Comment by mike2ox** [comment]
지금 PR용도를 초안 검토용으로 사용하는 거로 알고 있습니다.

**Comment by MijeongJeon** [comment]
넵, PR 올려주시면 저와 멘티분들께서 리뷰해주실거에요~!

**Comment by insurgent92** [comment]
@Las-Wonho @mike2ox  @MijeongJeon PR을 이용하는군요! 감사합니다!
