### ISSUE TITLE
케라스 LSTM 모델로 작곡하기

### ISSUE THREAD

**Issue by MijeongJeon** [KerasKorea/KEKOxTutorial#9]
### How to Generate Music using a LSTM Neural Network in Keras
[링크](https://towardsdatascience.com/how-to-generate-music-using-a-lstm-neural-network-in-keras-68786834d4c5)

**Comment by mike2ox** [comment]
건의 사항
1. 영문 표기 추가 
 - [gating mechanism](https://github.com/KerasKorea/KEKOxTutorial/blame/issue_09/09_%EC%BC%80%EB%9D%BC%EC%8A%A4%20LSTM%20%EB%AA%A8%EB%8D%B8%EB%A1%9C%20%EC%9E%91%EA%B3%A1%ED%95%98%EA%B8%B0.md#L25)
 - [Note & Chord](https://github.com/KerasKorea/KEKOxTutorial/blame/issue_09/09_%EC%BC%80%EB%9D%BC%EC%8A%A4%20LSTM%20%EB%AA%A8%EB%8D%B8%EB%A1%9C%20%EC%9E%91%EA%B3%A1%ED%95%98%EA%B8%B0.md#L28)

2. 단어 변경
- [트레인 셋 -> 학습 데이터셋](https://github.com/KerasKorea/KEKOxTutorial/blame/issue_09/09_%EC%BC%80%EB%9D%BC%EC%8A%A4%20LSTM%20%EB%AA%A8%EB%8D%B8%EB%A1%9C%20%EC%9E%91%EA%B3%A1%ED%95%98%EA%B8%B0.md#L88)

3. 의문 
- [line 272](https://github.com/KerasKorea/KEKOxTutorial/blame/issue_09/09_%EC%BC%80%EB%9D%BC%EC%8A%A4%20LSTM%20%EB%AA%A8%EB%8D%B8%EB%A1%9C%20%EC%9E%91%EA%B3%A1%ED%95%98%EA%B8%B0.md#L88)

4. 원문 외 내용(@parkjh688 님의 의견)은 '>'인용문 형식으로 바꿔서 본문과의 차이점을 부각 해주셨으면 합니다.

**Comment by parkjh688** [comment]
@mike2ox 

고맙습니다!

2, 4번은 이해했고 말씀하신대로 바꾸는 것이 좋을 것 같습니다!

1. 영문 표기 추가는 미정님이 올려주신 **01_guide_documtent.md** 에서 **주요키워드** 말씀하시는건가요?

3. 의문은 표현이 어렵다는 것인가요?

**Comment by mike2ox** [comment]
@parkjh688 

원문과 1:1매칭하면서 추가/수정했으면 좋을 부분을 남겼는데

> 1번에서 노드와 코드가 발음 그대로 적혀있었는데 `코드` 같은 경우엔 
> `Chord`인지 `Code`인지 번역문만 봐선 명확하지 않더라구요(뒤에 가선 이해했다만..)
> gating mechanism은 teacher forcing이라는 학습단계에서의 중요 개념과 동등한 급이라 생각해서
> 되도록이면 찾아보기 쉽도록 영문표기가 어떨까 싶어서 건의사항에 넣었습니다.

> 2번은 다른 line의 내용을 연결하려 했는데 지금 못찾겠네요;;
> 그래도 전반적으론 `4번`을 적용하면 해결될 듯 싶습니다.

**Comment by parkjh688** [comment]
아하 굳이 해석해놓지 않고 그렇게 하는게 더 좋겠네요.

제 의견을 넣은 부분도 '>' 인용문으로 바꾸겠습니다. 고맙습니다!

**Comment by MijeongJeon** [comment]
정현님, 문혁님 수고많으셨습니다!
이슈 클로즈 이후에도 언제든지 내용 추가/수정은 가능하답니다 :)

**Comment by insurgent92** [comment]
https://github.com/KerasKorea/KEKOxTutorial/pull/102#issue-216327118

**Comment by MijeongJeon** [comment]
#107 

정현님~ 조금 수정한 내용 확인 후 머지 부탁드립니다!
