### ISSUE TITLE
#40 issue_40 의 RP을 어떻게 진행하면 좋을까요? 

### ISSUE THREAD

**Issue by insurgent92** [KerasKorea/KEKOxTutorial#92]
안녕하세요~! 
현재 issue_40은 
https://github.com/fchollet/deep-learning-with-python-notebooks 을 진행하고 있습니다. 
전체 19개의 jupyter notebook 문서로 이루어져 있어서 양이 상당합니다. 
따라서 19개를 모두 완료한 뒤 풀리퀘스트가 올라가면 리뷰해야 할 양이 방대하다는 점이 우려됩니다. 
한 번에 풀 리퀘스크를 날리더라도 물론 여러 명이 파트를 나눠서 리뷰를 하면 되기 하겠지만.
혹시 좋은 방법이 없을까요?

**Comment by MijeongJeon** [comment]
19개면 정말 작업 분량이 많긴하네요, 급하게 마무리 지을 작업은 아니니 천천히 진행되는대로 파트를 나눠서 PR 올려주시면 될것 같아요~~ 파트 1 올려서 리뷰받는 동안 다음 파트 작업하는 방식으로...어떨까요?

**Comment by mike2ox** [comment]
양이 매우 많은 관계로 중복되지 않는 내용을 가진 파일만 번역하던지 다음 컨트리뷰톤 업무로 넘기면 어떨까 합니다.
